const { chromium } = require('@playwright/test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const base = process.env.TELEMETRY_BROWSER_URL || 'http://localhost';
const password=process.env.TELEMETRY_TEST_PASSWORD;
assert(password,'test password supplied by runner');
const results = [];
(async () => {
  const browser = await chromium.launch({headless:true});
  const context = await browser.newContext({baseURL:base});
  const page = await context.newPage();
  const fixture = async op => {
    const response = await context.request.get('/telemetry-test-fixture.php?op='+op);
    const text = await response.text();
    assert(response.ok(),text.slice(-2000));
    try { return JSON.parse(text); } catch { throw new Error(text.slice(-2500)); }
  };
  const state = () => fixture('state');
  await page.goto('/index.php');
  await page.locator('#username').fill('Synthetic1');
  await page.locator('#password').fill(password);
  await Promise.all([page.waitForURL('**/game.php*'),page.locator('#login').evaluate(form=>form.submit())]);
  assert((await page.content()).includes('game.php?page=buildings'));
  let data=await state();
  assert(data.events.some(e=>e.actor===1 && e.kind==='login'));
  const actor = data.users.find(u=>u.username==='Synthetic1');
  const target = data.users.find(u=>u.username==='Synthetic2');
  assert.equal(actor.id,1);
  const count = (data,kind) => data.events.filter(e=>e.actor===1 && e.kind===kind).length;
  let sends=count(data,'fleet.send');
  let response=await context.request.get('/game.php?page=fleetAjax&ajax=1&mission=6&planetID='+target.id_planet);
  assert.equal((await response.json()).code,600);
  data=await state();assert.equal(count(data,'fleet.send'),sends+1);
  const beforeReject=count(data,'fleet.send');
  response=await context.request.get('/game.php?page=fleetAjax&ajax=1&mission=6&planetID=0');
  assert.equal((await response.json()).code,601);
  assert.equal(count(await state(),'fleet.send'),beforeReject);
  results.push('successful and rejected actual AJAX fleet routes');
  let before=count(await state(),'queue.buildings');
  const mineBefore=(await state()).planets.find(p=>p.id===actor.id_planet).metal_mine;
  response=await context.request.post('/game.php?page=buildings&ajax=1',{form:{cmd:'insert',building:'1'}});
  assert(response.ok(),(await response.text()).slice(-1500));
  data=await state();assert.equal(count(data,'queue.buildings'),before+1);
  const built=data.planets.find(p=>p.id===actor.id_planet);
  assert(built.b_building_id!=='' || built.metal_mine>mineBefore);
  const readBefore=count(data,'galaxy.view');
  for(let i=0;i<3;i++) {
    response=await context.request.get('/game.php?page=galaxy&galaxy=1&system=12');
    assert(response.ok(),(await response.text()).slice(-1500));
  }
  data=await state();
  assert(count(data,'galaxy.view')>=readBefore+3);
  assert.equal(data.events.filter(e=>e.actor===target.id).length,0);
  results.push('queue persistence and repeated unchanged galaxy views attributed to the reader');
  await fixture('rollback_on');
  data=await state();before=count(data,'fleet.send');
  const fleetCount=data.fleets.length;
  response=await context.request.get('/game.php?page=fleetAjax&ajax=1&mission=6&planetID='+target.id_planet);
  assert.equal(response.status(),503);
  data=await state();assert.equal(count(data,'fleet.send'),before);assert.equal(data.fleets.length,fleetCount);
  before=count(data,'queue.buildings');
  response=await context.request.post('/game.php?page=buildings&ajax=1',{form:{cmd:'insert',building:'2'}});
  assert.equal(response.status(),503);
  assert.equal(count(await state(),'queue.buildings'),before);
  await fixture('rollback_off');
  results.push('actual fleet and economy persistence failures roll back game and success evidence');
  response=await context.request.post('/game.php?page=fleetStep1',{form:{ship202:'50'}});
  let html=await response.text();
  const match=html.match(/name="token" value="([^"]+)"/);
  assert(match,html.slice(-2000));
  const token=match[1];
  response=await context.request.post('/game.php?page=fleetStep2',{form:{token,galaxy:'1',system:'12',planet:'5',type:'1',speed:'10',target_mission:'3'}});
  assert(response.ok(),(await response.text()).slice(-1500));
  response=await context.request.post('/game.php?page=fleetStep3',{form:{token,mission:'3',metal:'200000',crystal:'0',deuterium:'0'}});
  assert(response.ok(),(await response.text()).slice(-2000));
  data=await state();assert(data.fleets.some(f=>f.fleet_resource_metal===200000));
  const targetBefore=data.planets.find(p=>p.id===target.id_planet).metal;
  await fixture('deliver');
  data=await state();
  assert.equal(data.planets.find(p=>p.id===target.id_planet).metal,targetBefore+200000);
  assert.equal(count(data,'delivery'),1);
  results.push('three-step transport request and actual delivery mission');
  // A completed recall cannot be recorded twice.
  const recalled=data.fleets.find(f=>f.fleet_owner===1 && f.fleet_mess===0);
  assert(recalled);
  const recallsBefore=count(data,'fleet.recall');
  response=await context.request.get('/game.php?page=fleetTable&action=sendfleetback&fleetID='+recalled.fleet_id);
  assert(response.ok(),(await response.text()).slice(-2000));
  data=await state();
  assert.equal(count(data,'fleet.recall'),recallsBefore+1);
  assert(data.events.some(e=>e.kind==='fleet.recall' && e.fleet_id===recalled.fleet_id));
  await context.request.get('/game.php?page=fleetTable&action=sendfleetback&fleetID='+recalled.fleet_id);
  assert.equal(count(await state(),'fleet.recall'),recallsBefore+1);
  results.push('actual fleet recall and repeated recall rejection');

  const latency=[];
  for (const fault of ['refused','permission','timeout','locked','disabled','reset']) {
    await fixture('fault_'+fault);
    const queryBefore=(await fixture('sql_count')).telemetry_queries;
    const beforeState=await state();
    const sentBefore=count(beforeState,'fleet.send');
    const beforeFleets=beforeState.fleets.length;
    for (const action of ['login','fleet','economy']) {
      const start=Date.now();
      if(action==='login') {
        await context.clearCookies();
        response=await context.request.post('/index.php?page=login',{form:{username:'Synthetic1',password},maxRedirects:0});
        assert.equal(response.status(),302);
        assert(response.headers().location.endsWith('game.php'),'fresh login succeeded');
      } else if(action==='fleet') {
        response=await context.request.get('/game.php?page=fleetAjax&ajax=1&mission=6&planetID='+target.id_planet);
        const body=await response.text();
        assert(body.startsWith('{'),fault+' fleet response: '+body.slice(-3000));
        assert.equal(JSON.parse(body).code,600);
      } else {
        response=await context.request.post('/game.php?page=buildings&ajax=1',{form:{cmd:'insert',building:'1'},maxRedirects:0});
        assert.equal(response.status(),302);
      }
      const elapsed=Date.now()-start;
      latency.push({fault,action,ms:elapsed});
      assert(elapsed<2500, fault+' '+action+' exceeded 2500ms: '+elapsed);
    }
    const afterState=await state();
    assert.equal(afterState.fleets.length,beforeFleets+1);
    assert.equal(count(afterState,'login'),count(beforeState,'login')+(fault==='reset'?1:0),fault+' login evidence');
    assert.equal(count(afterState,'fleet.send'),sentBefore+(fault==='reset'?1:0),fault+' success evidence');
    if(fault==='disabled') assert.equal((await fixture('sql_count')).telemetry_queries,queryBefore);
  }
  fs.writeFileSync('tests/telemetry/results/latency.json',JSON.stringify(latency,null,2));
  results.push('actual login, fleet and economy requests under refusal, permissions, timeout, row locks, disabled collection and recovery');
  await fixture('clear_activity');
  for (const route of ['buildings','research','overview','shipyard']) {
    response=await context.request.get('/game.php?page='+route+'&passive_reload=queue');
    assert(response.ok());
  }
  assert.equal((await state()).activity.length,0,'automatic reloads add no activity');
  response=await context.request.get('/game.php?page=fleetTable',{headers:{'X-Forwarded-For':'198.51.100.8'}});
  assert(response.ok());
  assert.equal((await state()).activity.length,1,'manual fleet page records interaction');
  results.push('actual passive page requests versus manual fleet page activity');
  const mobileAgent='Mozilla/5.0 (Linux; Android 14) AppleWebKit/537.36 Chrome/140.0 Mobile Safari/537.36';
  await context.request.get('/game.php?page=fleetTable',{headers:{'User-Agent':mobileAgent,'X-Forwarded-For':'198.51.100.8'}});
  data=await state();
  const mobileRows=data.events.filter(e=>e.actor===1 && e.kind==='interaction' && JSON.parse(e.data).client==='Chrome · Android · mobile');
  assert(mobileRows.length);
  assert(mobileRows.every(e=>e.ip!=='198.51.100.8'),'forwarded IP never trusted');
  await fixture('network_off');
  await context.request.get('/game.php?page=galaxy&galaxy=1&system=12',{headers:{'User-Agent':mobileAgent}});
  data=await state();
  const lastRead=data.events.filter(e=>e.kind==='galaxy.view').at(-1);
  assert.equal(lastRead.ip,null);
  assert.equal(JSON.parse(lastRead.data).client,undefined,'network switch disables client recording');
  await fixture('network_on');

  await fixture('workflow');
  await page.goto('/admin.php');
  await page.locator('[name=admin_pw]').fill(password);
  await Promise.all([page.waitForNavigation(),page.locator('[name=admin_pw]').evaluate(input=>input.form.submit())]);
  await page.goto('/admin.php?page=telemetry');
  await page.locator('h1').filter({hasText:'Activité des joueurs'}).waitFor();
  assert(!(await page.locator('.telemetry').innerText()).includes('indisponible'));
  data=await state();
  const warning=data.warnings.find(w=>w.actor===1 && w.kind==='workflow');
  assert(warning);
  assert.equal(await page.locator('#telemetry-timezone').count(),0,'timezone selector stays off the home page');
  const playerLink=page.locator('.account-list a[href="?page=telemetry&account=1"]');
  assert.equal(await playerLink.count(),1,'one queue row per account');
  assert.equal(await playerLink.innerText(),'Synthetic1 (1)');
  const openCount=data.warnings.filter(w=>w.status==='open' && (w.actor===1 || w.other===1)).length;
  assert.equal(Number(await playerLink.locator('xpath=../..').locator('td').nth(1).innerText()),openCount,'queue counts every warning for the account');
  await playerLink.click();
  assert.equal(await page.locator('#player-warnings tbody tr').count(),data.warnings.filter(w=>w.actor===1 || w.other===1).length,'player page collects all warnings');
  assert.equal(await page.locator('.heat').count(),7,'single player heatmap contains seven days');
  assert(!(await page.locator('.telemetry').innerText()).includes('Une interaction compte'));
  await page.goto('/admin.php?page=telemetry&view=settings');
  assert.equal(await page.locator('#telemetry-timezone').inputValue(),'Europe/Paris','default review timezone is Paris');
  await page.locator('#telemetry-timezone').selectOption('UTC');
  await Promise.all([page.waitForNavigation(),page.locator('.timezone-form button').click()]);
  assert.equal(new URL(page.url()).searchParams.get('view'),'settings');
  assert.equal(await page.locator('#telemetry-timezone').inputValue(),'UTC');
  await page.goto('/admin.php?page=telemetry&id='+warning.id);
  assert((await page.locator('.timeline').first().innerText()).includes('UTC'),'timezone applies to warning dates');
  assert((await page.locator('.telemetry').innerText()).includes('Séquence répétée'));
  assert(await page.locator('.timeline').first().locator('tbody tr').count()>=30);
  assert((await page.locator('.telemetry').innerText()).includes('Autres observations'));
  data=await state();
  assert(JSON.parse(data.warnings.find(w=>w.id===warning.id).latest_evidence).matches,'opening warning reruns analysis');
  const csrf=await page.locator('input[name=token]').first().inputValue();
  response=await context.request.post('/admin.php?page=telemetry&id='+warning.id,{form:{action:'review',id:String(warning.id),token:csrf,status:'follow_up',note:'Vérification synthétique <script>test</script>'}});
  assert(response.ok());
  assert((await response.text()).includes('Décision enregistrée'));
  data=await state();assert.equal(data.warnings.find(w=>w.id===warning.id).status,'follow_up');
  assert((await response.text()).includes('&lt;script&gt;test&lt;/script&gt;'));
  response=await context.request.post('/admin.php?page=telemetry&id='+warning.id,{form:{action:'review',id:String(warning.id),token:'forged',status:'dismissed',note:'forged'}});
  assert((await response.text()).includes('Formulaire expiré'));
  assert.equal((await state()).warnings.find(w=>w.id===warning.id).status,'follow_up');
  await page.goto('/admin.php?page=telemetry');
  await page.goto('/admin.php?page=telemetry&view=settings');
  assert.equal(await page.locator('.account-list').count(),0,'settings has its own page');
  assert.equal(await page.locator('#telemetry-events_enabled').getAttribute('type'),'checkbox');
  await page.locator('#telemetry-network_enabled').uncheck();
  await page.locator('#telemetry-group-pushing > summary').click();
  assert.equal(await page.locator('#telemetry-imbalance_allowance').inputValue(),'25','fractions shown as percentages');
  await page.locator('#telemetry-imbalance_allowance').fill('30');
  await Promise.all([page.waitForNavigation(),page.locator('button[type=submit]').filter({hasText:'Enregistrer les réglages'}).click()]);
  assert((await page.locator('.telemetry').innerText()).includes('Réglages enregistrés'));
  assert.equal(await page.locator('#telemetry-network_enabled').isChecked(),false,'unchecked setting saves as off');
  assert.equal(await page.locator('#telemetry-imbalance_allowance').inputValue(),'30','percentage survives a save');
  await page.locator('#telemetry-group-pushing > summary').click();
  await page.locator('#telemetry-push_minimum').fill('123456');
  await page.locator('#telemetry-event_days').fill('1');
  await Promise.all([page.waitForNavigation(),page.locator('button[type=submit]').filter({hasText:'Enregistrer les réglages'}).click()]);
  assert((await page.locator('.telemetry').innerText()).includes('Conservez les actions détaillées au moins 7 jours'));
  assert.equal(await page.locator('#telemetry-push_minimum').inputValue(),'100000');
  await page.getByRole('button',{name:'Rétablir les valeurs par défaut'}).click();
  assert.equal(await page.locator('#telemetry-network_enabled').isChecked(),true);
  assert.equal(await page.locator('#telemetry-imbalance_allowance').inputValue(),'25');
  await Promise.all([page.waitForNavigation(),page.getByRole('button',{name:'Enregistrer les réglages',exact:true}).click()]);
  assert.equal(await page.locator('#telemetry-network_enabled').isChecked(),true,'checked setting saves as on');
  await page.screenshot({path:'tests/telemetry/results/settings.png',fullPage:true});
  await fixture('workflow_remove');
  await page.goto('/admin.php?page=telemetry&id='+warning.id);
  assert((await page.locator('.telemetry').innerText()).includes('Les seuils ne sont plus atteints'));
  assert.equal((await state()).warnings.find(w=>w.id===warning.id).status,'follow_up');
  await page.goto('/admin.php?page=telemetry&account=1&other=2');
  await page.locator('.heat').first().waitFor();
  assert.equal(await page.locator('.heat').count(),14,'both accounts have all seven aligned days');
  const comparison=await page.locator('table.comparison').first().innerText();
  assert(comparison.includes('Durée active estimée / jour') && comparison.includes('Synthetic1') && comparison.includes('Synthetic2'));
  await page.getByText('Adresses IP et clients utilisés',{exact:true}).click();
  assert((await page.locator('table.network').first().innerText()).includes('Chrome · Android · mobile'),await page.locator('table.network').first().innerText());
  await page.screenshot({path:'tests/telemetry/results/admin.png',fullPage:true});
  await page.goto('/admin.php?page=telemetry&account=1&timezone=Europe%2FParis');
  assert((await page.locator('#player-warnings').innerText()).includes('À suivre'),'player page includes reviewed warnings');
  await page.screenshot({path:'tests/telemetry/results/player.png',fullPage:true});
  await fixture('permissions');
  const ordinary=await browser.newContext({baseURL:base});
  await ordinary.request.post('/index.php?page=login',{form:{username:'Synthetic2',password:password}});
  const denied=await ordinary.request.get('/admin.php?page=telemetry',{maxRedirects:0});
  assert.equal(denied.status(),302);
  assert(denied.headers().location.includes('game.php'));
  await ordinary.close();
  await page.goto('/admin.php?page=accountdata&id_u=2');
  assert.equal(await page.locator('a[href="?page=telemetry&account=2"]').count(),1,'account page links to activity');
  await page.goto('/admin.php?page=module');
  let moduleRow=page.locator('tr').filter({has:page.locator('td').filter({hasText:/^Activité des joueurs$/})});
  assert.equal(await moduleRow.count(),1,'telemetry listed in Modules');
  const disable=await moduleRow.locator('a').getAttribute('href');
  const currentEvents=(await state()).events.length;
  await page.goto('/admin.php'+disable.replace(/&sid=[^&]+/,''));
  await context.request.get('/game.php?page=galaxy&galaxy=1&system=12');
  assert((await state()).events.length>currentEvents,'unsigned module toggle rejected');
  await page.goto('/admin.php'+disable);
  const disabledEvents=(await state()).events.length;
  await context.request.get('/game.php?page=galaxy&galaxy=1&system=12');
  assert.equal((await state()).events.length,disabledEvents,'module off stops collection even for admin');
  await page.goto('/admin.php?page=telemetry&id='+warning.id);
  await page.locator('#telemetry-health > summary').click();
  assert((await page.locator('.telemetry').innerText()).includes('Désactivée'),'saved warning stays readable while module off');
  await page.goto('/admin.php?page=module');
  moduleRow=page.locator('tr').filter({has:page.locator('td').filter({hasText:/^Activité des joueurs$/})});
  await Promise.all([page.waitForNavigation(),moduleRow.locator('a').click()]);
  await context.request.get('/game.php?page=galaxy&galaxy=1&system=12');
  assert((await state()).events.length>disabledEvents,'module on resumes collection');
  assert((await state()).health.gaps.some(g=>g.reason==='disabled' && g.universe===1),'module switch retains collection gap');
  await fixture('moderator_on');
  const moderator=await browser.newContext({baseURL:base});
  const modPage=await moderator.newPage();
  await moderator.request.post('/index.php?page=login',{form:{username:'Synthetic2',password}});
  const noAdminSession=await moderator.request.get('/admin.php?page=telemetry');
  assert((await noAdminSession.text()).includes('admin_pw'),'moderator still needs admin login');
  await modPage.goto('/admin.php');
  await modPage.locator('[name=admin_pw]').fill(password);
  await Promise.all([modPage.waitForNavigation(),modPage.locator('[name=admin_pw]').evaluate(input=>input.form.submit())]);
  let noRight=await moderator.request.get('/admin.php?page=telemetry');
  assert.equal(noRight.status(),403,'existing page permission enforced');
  await modPage.goto('/admin.php?page=menu');
  assert.equal(await modPage.locator('a[href="?page=telemetry"]').count(),0,'menu follows page permission');
  await fixture('moderator_grant');
  await modPage.goto('/admin.php?page=telemetry');
  await modPage.locator('h1').filter({hasText:'Activité des joueurs'}).waitFor();
  await moderator.close();
  await fixture('moderator_off');
  results.push('module toggle, account link and existing moderator permissions');
  const {payload}=await fixture('escaped_fields');
  await context.request.get('/game.php?page=galaxy&galaxy=1&system=12',{headers:{'User-Agent':'Chrome/140.0 Android Mobile '+payload}});
  const lastEvent=(await state()).events.filter(e=>e.actor===1 && e.kind==='galaxy.view').at(-1);
  assert.equal(JSON.parse(lastEvent.data).client,'Chrome · Android · mobile','raw user agent is reduced to fixed labels');
  for (const route of ['/admin.php?page=telemetry','/admin.php?page=telemetry&account=2','/admin.php?page=telemetry&account=1&other=2']) {
    await page.goto(route);
    assert((await page.locator('.telemetry').textContent()).includes(payload),'untrusted name is displayed as text');
    assert.equal(await page.locator('.telemetry img').count(),0,'stored markup cannot create elements');
    assert.equal(await page.evaluate(()=>window.txss),undefined,'stored markup cannot run script');
  }
  await page.getByText('Adresses IP et clients utilisés',{exact:true}).click();
  assert((await page.locator('table.network').last().innerText()).includes(payload),'client text is escaped too');
  await page.goto('/admin.php?page=telemetry&id='+warning.id);
  assert((await page.locator('.telemetry').innerText()).includes('<script>test</script>'),'review note displays literally');
  assert.equal(await page.locator('.telemetry script').count(),0);
  results.push('stored names, client strings and review notes escaped; raw user agent discarded');
  results.push('rendered evidence, notes, settings validation, heatmap and moderator checks');
  await context.close();await browser.close();
  fs.writeFileSync('tests/telemetry/results/browser.json',JSON.stringify(results,null,2));
  console.log(results.join('\n'));
})().catch(error=>{console.error(error);process.exit(1);});
